#!/usr/bin/env bash
set -euo pipefail

pattern="${1:-}"

selected=$(rg --line-number --no-heading "$pattern" | fzf) || exit 0

IFS=: read -r file line _ <<< "$selected"

vim +$line "$file"

# vim: ft=bash
